const REPO='Futuristicbd/royel-cement-frame';
const API=`https://api.github.com/repos/${REPO}`;
const RAW=`https://raw.githubusercontent.com/${REPO}/main/`;
const app=document.querySelector('#app');
let campaigns=[],token='',catalogSha=null,toastTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4200)}
function sampleFrame(color='#07583f'){
 const c=document.createElement('canvas');c.width=c.height=1080;const x=c.getContext('2d');
 x.fillStyle=color;x.fillRect(0,0,1080,148);x.fillRect(0,898,1080,182);x.fillRect(0,0,24,1080);x.fillRect(1056,0,24,1080);
 x.fillStyle='#d4ec89';x.fillRect(24,148,1032,7);x.fillRect(24,891,1032,7);
 x.font='bold 49px Arial';x.fillStyle='#fff';x.fillText('ROYAL CEMENT',55,87);x.font='20px Arial';x.fillStyle='#d4ec89';x.fillText('CAMPAIGN FRAME',765,83);
 x.font='bold 46px Arial';x.fillStyle='#fff';x.fillText('BUILDING TOGETHER.',55,976);x.font='24px Arial';x.fillStyle='#d4ec89';x.fillText('Strong foundations. Shared moments.',57,1030);
 return c.toDataURL('image/png');
}
function frameURL(frame){return frame.demo?sampleFrame(frame.color):`${RAW}${frame.path}`}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Image could not load. Please try again.'));i.src=src})}
function toBase64(text){const bytes=new TextEncoder().encode(text);let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function fromBase64(text){return new TextDecoder().decode(Uint8Array.from(atob(text.replace(/\s/g,'')),c=>c.charCodeAt(0)))}
async function github(path,options={}){
 const r=await fetch(`${API}${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'Content-Type':'application/json',...options.headers}});
 if(!r.ok){let data={};try{data=await r.json()}catch{};throw Error(r.status===409?'Another admin changed this campaign. Reload before saving again.':r.status===401?'This token is invalid or expired. Please sign in again.':r.status===403?'GitHub denied access. Check Contents: Read and write permission, or try again after the rate limit resets.':data.message||`Request failed (${r.status}).`)}
 return r.status===204?null:r.json();
}
async function getCampaigns(){
 const r=await fetch(`${RAW}data/campaigns.json?t=${Date.now()}`,{cache:'no-store'});
 if(!r.ok)throw Error('Campaigns are temporarily unavailable. Please reload.');
 const data=await r.json();if(!Array.isArray(data.campaigns))throw Error('Campaign data could not be read.');return data.campaigns;
}
async function copy(text){if(!navigator.clipboard)throw Error('Clipboard is unavailable. Select and copy the caption below.');await navigator.clipboard.writeText(text)}
function bindCopy(selector,text,message='Copied!'){const b=$(selector);if(b)b.onclick=async()=>{try{await copy(text);toast(message)}catch{toast('Could not copy automatically. Select the text and copy it.')}}}
function linkFor(c){return `${location.origin}/c/${encodeURIComponent(c.slug)}`}
function showError(message){app.innerHTML=`<div class="empty-state"><h1>Unable to load</h1><p>${esc(message)}</p><button class="button" id="retry">Try again</button></div>`;$('#retry').onclick=()=>location.reload()}
function home(){
 const active=campaigns.filter(c=>c.published);
 app.innerHTML=`<div class="hero-strip"><div><p class="eyebrow" style="color:#d4ec89">Royal Cement · Campaigns</p><h1>Your photo. Our shared story.</h1><p>আপনার ছবি যোগ করুন, ফ্রেমে সাজান, সবার সাথে শেয়ার করুন।</p></div><div class="hero-label"><strong>UPLOAD. ADJUST. SHARE.</strong><br>Your photo stays on your device.</div></div><div class="page-heading"><div><h2>Choose your campaign</h2><p class="sub">A frame for every moment.</p></div><span class="sub">${active.length} campaign${active.length===1?'':'s'}</span></div><div class="grid">${active.map(c=>`<article class="campaign-card"><a href="/c/${esc(c.slug)}" class="card-preview" style="display:block"><img src="${esc(frameURL(c.frames[0]))}" alt="${esc(c.title)} frame"></a><div class="card-info"><span class="badge">${c.id==='demo'?'SAMPLE CAMPAIGN':'CAMPAIGN'}</span><h3>${esc(c.title)}</h3><p>${esc(c.description||'Add your photo and join the campaign.')}</p><a class="button" href="/c/${esc(c.slug)}">Create your photo <span>↗</span></a></div></article>`).join('')}</div>${!active.length?'<div class="empty-state">No campaigns are live yet. Please check back soon.</div>':''}`;
}
async function editor(c){
 document.title=`${c.title} | Royal Cement`;
 app.innerHTML=`<a class="back" href="/">← All campaigns</a><div class="page-heading"><div><p class="eyebrow">Royal Cement · ${c.id==='demo'?'Sample campaign':'Campaign'}</p><h1>${esc(c.title)}</h1><p class="sub">${esc(c.description||'আপনার ছবি দিয়ে ক্যাম্পেইনে অংশ নিন।')}</p></div><button class="button quiet" id="share-link">↗ <span>Share link</span></button></div><div class="editor-layout"><div><div class="preview-area"><div class="preview-top"><span>YOUR CAMPAIGN PHOTO</span><span>1 : 1</span></div><div class="canvas-wrap"><canvas id="canvas" width="1080" height="1080" tabindex="0" aria-label="Photo preview. Drag to reposition, or use arrow keys after uploading a photo."></canvas><div class="empty-photo" id="empty-photo"><div class="photo-symbol">▧</div><strong>Your photo goes here</strong><p>Upload a photo to make it yours</p></div></div><p class="preview-bottom">Drag to reposition · Pinch or use the slider to zoom</p></div><div class="toolbar"><button class="icon-button" id="zoom-out" aria-label="Zoom out" disabled>−</button><button class="icon-button" id="zoom-in" aria-label="Zoom in" disabled>+</button><span class="divider"></span><button class="icon-button" id="rotate" aria-label="Rotate photo 90 degrees" disabled>↻</button><button class="button quiet" id="reset" disabled>Reset</button></div></div><div><section class="panel-section"><div class="section-title"><span class="step">1</span><h2>Add your photo</h2></div><label class="upload-zone" id="photo-drop" tabindex="0" role="button"><span class="upload-icon">↥</span><strong id="photo-label">Choose a photo</strong><small>JPG, PNG or WebP · Up to 20 MB</small><input id="photo-input" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="zoom-label"><label for="zoom">Photo zoom</label><span id="zoom-value">100%</span></div><input id="zoom" type="range" min="1" max="4" step=".01" value="1" disabled></section><section class="panel-section"><div class="section-title"><span class="step">2</span><h2>Choose your frame</h2></div><div class="frame-options">${c.frames.map((f,i)=>`<button class="frame-option ${i===0?'selected':''}" data-frame="${i}" aria-label="Choose frame ${i+1}" aria-pressed="${i===0}"><img src="${esc(frameURL(f))}" alt="Frame ${i+1}"></button>`).join('')}</div><button id="download" class="button primary full download" disabled>↓ Download photo</button><p class="checkline">1080 × 1080 PNG · No watermark</p></section><section class="panel-section"><div class="caption-head"><h2>Campaign caption</h2><button id="copy-caption" class="copy">▣ Copy caption</button></div><div class="caption-box" tabindex="0">${esc(c.caption||'')}</div><button id="download-copy" class="button full" style="margin-top:14px" disabled>↓ Download + copy caption</button></section><p class="help" style="text-align:center;margin-top:18px">আপনার ছবি সার্ভারে আপলোড করা হয় না।</p></div></div>`;
 bindCopy('#share-link',linkFor(c),'Campaign link copied');bindCopy('#copy-caption',c.caption,'Caption copied');
 const canvas=$('#canvas'),ctx=canvas.getContext('2d');let photo=null,frame=null,angle=0,zoom=1,dx=0,dy=0,frameRequest=0,photoRequest=0;const pointers=new Map();let pinchDistance=0;
 function fit(){if(!photo)return {w:0,h:0};const rotated=angle%180!==0;const pw=rotated?photo.height:photo.width,ph=rotated?photo.width:photo.height;const scale=Math.max(1080/pw,1080/ph)*zoom;return {w:photo.width*scale,h:photo.height*scale,bw:pw*scale,bh:ph*scale}}
 function draw(){ctx.clearRect(0,0,1080,1080);ctx.fillStyle='#f8faf6';ctx.fillRect(0,0,1080,1080);if(photo){const s=fit();dx=Math.max(-(s.bw-1080)/2,Math.min((s.bw-1080)/2,dx));dy=Math.max(-(s.bh-1080)/2,Math.min((s.bh-1080)/2,dy));ctx.save();ctx.translate(540+dx,540+dy);ctx.rotate(angle*Math.PI/180);ctx.drawImage(photo,-s.w/2,-s.h/2,s.w,s.h);ctx.restore()}if(frame)ctx.drawImage(frame,0,0,1080,1080);$('#zoom').value=zoom;$('#zoom-value').textContent=`${Math.round(zoom*100)}%`}
 function ready(){for(const id of ['download','download-copy'])$('#'+id).disabled=!(photo&&frame);for(const id of ['zoom','zoom-in','zoom-out','rotate','reset'])$('#'+id).disabled=!photo}
 async function chooseFrame(i){const request=++frameRequest;frame=null;ready();draw();document.querySelectorAll('[data-frame]').forEach(b=>{b.classList.toggle('selected',+b.dataset.frame===i);b.setAttribute('aria-pressed',String(+b.dataset.frame===i))});try{const image=await loadImage(frameURL(c.frames[i]));if(request!==frameRequest)return;frame=image;draw();ready()}catch(e){if(request===frameRequest)toast(e.message)}}
 document.querySelectorAll('[data-frame]').forEach(b=>b.onclick=()=>chooseFrame(+b.dataset.frame));
 async function upload(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Please choose a JPG, PNG or WebP photo.');return}if(file.size>20*1024*1024){toast('Please choose a photo smaller than 20 MB.');return}const request=++photoRequest;const url=URL.createObjectURL(file);try{const image=await loadImage(url);if(request!==photoRequest)return;photo=image;angle=0;zoom=1;dx=dy=0;$('#empty-photo').hidden=true;$('#photo-label').textContent='Change photo';draw();ready();toast('Photo added. Drag to adjust.')}catch(e){toast(e.message)}finally{URL.revokeObjectURL(url);$('#photo-input').value=''}}
 $('#photo-input').onchange=e=>upload(e.target.files[0]);const drop=$('#photo-drop');drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#photo-input').click()}};drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');upload(e.dataTransfer.files[0])};
 function setZoom(v){zoom=Math.max(1,Math.min(4,v));draw()}
 $('#zoom').oninput=e=>setZoom(+e.target.value);$('#zoom-in').onclick=()=>setZoom(zoom+.1);$('#zoom-out').onclick=()=>setZoom(zoom-.1);$('#rotate').onclick=()=>{angle=(angle+90)%360;dx=dy=0;draw()};$('#reset').onclick=()=>{angle=0;zoom=1;dx=dy=0;draw()};
 canvas.onpointerdown=e=>{if(!photo)return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];pinchDistance=Math.hypot(a.x-b.x,a.y-b.y)}};
 canvas.onpointermove=e=>{const prev=pointers.get(e.pointerId);if(!prev)return;const ratio=1080/canvas.getBoundingClientRect().width;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinchDistance>0)setZoom(zoom*d/pinchDistance);pinchDistance=d}else{dx+=(e.clientX-prev.x)*ratio;dy+=(e.clientY-prev.y)*ratio;draw()}};
 canvas.onpointerup=canvas.onpointercancel=e=>{pointers.delete(e.pointerId);pinchDistance=0};canvas.onlostpointercapture=e=>pointers.delete(e.pointerId);
 canvas.onkeydown=e=>{if(!photo||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const amount=e.shiftKey?30:10;if(e.key==='ArrowLeft')dx-=amount;if(e.key==='ArrowRight')dx+=amount;if(e.key==='ArrowUp')dy-=amount;if(e.key==='ArrowDown')dy+=amount;draw()};
 function download(){return new Promise((resolve,reject)=>{if(!photo||!frame){reject(Error('Add your photo and wait for the frame to load.'));return}try{canvas.toBlob(blob=>{if(!blob){reject(Error('Download failed. Try again.'));return}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${c.slug}-royal-cement.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);resolve()},'image/png')}catch{reject(Error('The frame could not be exported. Reload and try again.'))}})}
 $('#download').onclick=async()=>{try{await download();toast('Your photo is ready to share.')}catch(e){toast(e.message)}};
 $('#download-copy').onclick=async()=>{const clipboard=copy(c.caption).then(()=>true,()=>false);try{await download();toast(await clipboard?'Photo downloaded and caption copied!':'Photo downloaded. Please copy the caption manually.')}catch(e){toast(e.message)}};
 await chooseFrame(0);
}
function login(){
 app.innerHTML=`<a class="back" href="/">← Back to campaigns</a><div class="form-card login"><p class="eyebrow">Campaign studio</p><h1>Admin sign in</h1><p class="sub" style="margin-bottom:26px">Manage your frames, captions and campaign links.</p><form id="login-form"><label class="field">GitHub access token<input id="token" type="password" autocomplete="off" required placeholder="github_pat_…" spellcheck="false"><span class="help">Use a fine-grained token for <strong>${REPO}</strong> with <strong>Contents: Read and write</strong>. Your token stays in memory and is cleared when this page closes.</span></label><button class="button primary full" id="login-button">Sign in</button><div id="login-error" role="alert"></div></form><p class="help" style="margin-top:23px"><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Create a GitHub access token ↗</a><br>Select “Only select repositories” → royel-cement-frame → Repository permissions → Contents: Read and write.</p></div>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();token=$('#token').value.trim();$('#login-button').disabled=true;$('#login-button').textContent='Signing in…';try{const repo=await github('');if(!repo.permissions?.push)throw Error('This account does not have write access to this repository.');await refreshAdmin();adminHome()}catch(err){token='';$('#login-error').innerHTML=`<p class="error">${esc(err.message)}</p>`;$('#login-button').disabled=false;$('#login-button').textContent='Sign in'}};
}
async function refreshAdmin(){const f=await github('/contents/data/campaigns.json?ref=main');catalogSha=f.sha;campaigns=JSON.parse(fromBase64(f.content)).campaigns}
async function saveCatalog(next){const result=await github('/contents/data/campaigns.json',{method:'PUT',body:JSON.stringify({message:'Update campaign frames and captions',branch:'main',sha:catalogSha,content:toBase64(JSON.stringify({campaigns:next},null,2))})});catalogSha=result.content.sha;campaigns=next}
function adminHome(){
 document.title='Admin | Royal Cement';app.innerHTML=`<div class="page-heading"><div><p class="eyebrow">Campaign studio</p><h1>Your campaigns</h1><p class="sub">Create a frame. Start a shared moment.</p></div><div class="admin-top"><button id="new-campaign" class="button primary">+ New campaign</button><button id="logout" class="button">Sign out</button></div></div><div class="admin-list">${campaigns.map(c=>`<article class="admin-row"><img src="${esc(frameURL(c.frames[0]))}" alt="Campaign frame"><div class="details"><span class="badge">${c.published?'PUBLISHED':'DRAFT'}</span><h3>${esc(c.title)}</h3><small>${c.frames.length} frame${c.frames.length===1?'':'s'} · /c/${esc(c.slug)}</small></div><div class="admin-actions"><button class="button" data-copy="${esc(c.id)}" ${c.published?'':'disabled'}>Copy link</button>${c.published?`<a class="button" href="/c/${esc(c.slug)}" target="_blank" rel="noopener">View ↗</a>`:''}<button class="button" data-edit="${esc(c.id)}">Edit</button><button class="button danger" data-delete="${esc(c.id)}">Delete</button></div></article>`).join('')}</div>${campaigns.length?'':'<div class="empty-state">Create your first campaign to upload a frame and caption.</div>'}<p class="help" style="margin-top:22px">Changes are saved to your GitHub repository. A published campaign link works for everyone, without signing in.</p>`;
 $('#new-campaign').onclick=()=>editCampaign();$('#logout').onclick=()=>{token='';catalogSha=null;login()};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editCampaign(campaigns.find(c=>c.id===b.dataset.edit)));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await copy(linkFor(campaigns.find(c=>c.id===b.dataset.copy)));toast('Campaign link copied')}catch{toast('Could not copy. Open View and copy the address.')}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const c=campaigns.find(c=>c.id===b.dataset.delete);if(!confirm(`Delete “${c.title}”? Its campaign link will no longer work.`))return;b.disabled=true;try{await saveCatalog(campaigns.filter(x=>x.id!==c.id));adminHome();toast('Campaign deleted')}catch(e){toast(e.message);b.disabled=false}});
}
function editCampaign(existing){
 const draft=existing?structuredClone(existing):{id:crypto.randomUUID(),title:'',slug:'',description:'',caption:'',published:true,frames:[]};let busy=false;
 app.innerHTML=`<button class="back" id="back-admin" style="border:0;background:none;cursor:pointer;padding:0">← All campaigns</button><div class="page-heading"><div><p class="eyebrow">Campaign studio</p><h1>${existing?'Edit campaign':'Create a campaign'}</h1><p class="sub">Upload your frame and write the caption people will share.</p></div></div><form id="campaign-form"><div class="edit-grid"><div class="form-card"><label class="field">Campaign name<input id="title" maxlength="100" required value="${esc(draft.title)}" placeholder="e.g. Feni Engineers Summit 2026"></label><label class="field">Campaign link<input id="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="80" value="${esc(draft.slug)}" placeholder="feni-engineers-summit-2026"><span class="help">${esc(location.origin)}/c/<span id="slug-preview">${esc(draft.slug||'your-campaign')}</span>${existing?' · Changing this breaks the old link.':''}</span></label><label class="field">Short description<input id="description" maxlength="200" value="${esc(draft.description)}" placeholder="আপনার ছবি দিয়ে ক্যাম্পেইনে অংশ নিন।"></label><label class="field">Caption<textarea id="caption" maxlength="5000" required placeholder="Write the caption people can copy…">${esc(draft.caption)}</textarea></label><label class="field">Visibility<select id="published"><option value="true" ${draft.published?'selected':''}>Published — anyone with the link</option><option value="false" ${!draft.published?'selected':''}>Draft — hidden from visitors</option></select></label></div><div class="form-card"><h2>Campaign frames</h2><p class="sub">Square PNGs with a transparent photo area.</p><div id="frame-list" class="frame-list"></div><label class="upload-zone" tabindex="0" role="button" id="frame-zone"><span class="upload-icon">＋</span><strong>Add frame</strong><small>Square transparent PNG · Up to 3 MB each · Max 6</small><input id="frame-input" type="file" accept="image/png" multiple></label><p class="notice">ফ্রেমের মাঝের অংশ transparent রাখুন। আপনার ফ্রেম ছবির উপরে বসবে। 1080 × 1080 px বা তার বড় square PNG ব্যবহার করুন।</p><p class="help">Upload only campaign artwork here. Visitors’ personal photos are never saved.</p></div></div><div id="save-error" role="alert"></div><div class="actions"><button class="button primary" type="submit" id="save-button">Save campaign</button><button class="button" type="button" id="cancel">Cancel</button><span class="status-line" id="save-status" role="status"></span></div></form>`;
 const back=()=>{if(!busy)adminHome()};$('#back-admin').onclick=back;$('#cancel').onclick=back;
 $('#title').oninput=e=>{if(!existing&&!$('#slug').dataset.touched){$('#slug').value=e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);$('#slug-preview').textContent=$('#slug').value||'your-campaign'}};$('#slug').oninput=e=>{e.target.dataset.touched='true';$('#slug-preview').textContent=e.target.value||'your-campaign'};
 function renderFrames(){const list=$('#frame-list');list.innerHTML=draft.frames.map((f,i)=>`<div class="admin-frame"><img src="${esc(f.data||frameURL(f))}" alt="Frame ${i+1}"><button type="button" data-remove="${i}">Remove frame ${i+1}</button></div>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(busy)return;draft.frames.splice(+b.dataset.remove,1);renderFrames()})}
 renderFrames();$('#frame-zone').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#frame-input').click()}};
 $('#frame-input').onchange=async e=>{if(busy)return;busy=true;$('#save-button').disabled=true;try{for(const file of e.target.files){if(draft.frames.length>=6)throw Error('You can add up to 6 frames per campaign.');if(file.type!=='image/png'||file.size>3*1024*1024)throw Error('Frames must be PNG files smaller than 3 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('File could not be read.'));reader.readAsDataURL(file)});const img=await loadImage(data);if(img.width!==img.height||img.width<500||img.width>6000)throw Error('Use a square frame between 500 × 500 and 6000 × 6000 px.');const cv=document.createElement('canvas');cv.width=cv.height=100;const cx=cv.getContext('2d',{willReadFrequently:true});cx.drawImage(img,0,0,100,100);const px=cx.getImageData(0,0,100,100).data;let transparent=0;for(let i=3;i<px.length;i+=4)if(px[i]<240)transparent++;if(transparent<100)throw Error('This frame has no usable transparent photo area. Export it as a transparent PNG.');draft.frames.push({id:crypto.randomUUID(),data});renderFrames()}toast('Frame added')}catch(err){toast(err.message)}finally{busy=false;$('#save-button').disabled=false;e.target.value=''}};
 $('#campaign-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const title=$('#title').value.trim(),slug=$('#slug').value.trim(),caption=$('#caption').value.trim();if(!title||!caption){toast('Add a campaign name and caption.');return}if(!draft.frames.length){toast('Add at least one frame.');return}if(campaigns.some(c=>c.id!==draft.id&&c.slug===slug)){toast('That campaign link is already in use. Choose another.');return}busy=true;$('#save-button').disabled=true;$('#save-error').innerHTML='';$('#save-status').textContent='Saving frames…';try{const frames=[];for(const f of draft.frames){if(!f.data){frames.push(f);continue}const path=`frames/${f.id}.png`;await github(`/contents/${path}`,{method:'PUT',body:JSON.stringify({branch:'main',message:`Add frame for ${title}`,content:f.data.split(',')[1]})});delete f.data;f.path=path;frames.push({...f})}$('#save-status').textContent='Saving campaign…';const result={id:draft.id,title,slug,description:$('#description').value.trim(),caption,published:$('#published').value==='true',frames,updatedAt:new Date().toISOString()};const next=existing?campaigns.map(c=>c.id===draft.id?result:c):[result,...campaigns];await saveCatalog(next);busy=false;adminHome();toast('Campaign saved. Your share link is ready.')}catch(err){$('#save-error').innerHTML=`<p class="error">${esc(err.message)}</p>`;$('#save-status').textContent='';busy=false;$('#save-button').disabled=false}};
}
async function start(){const path=location.pathname.replace(/\/$/,'')||'/';if(path==='/admin'){login();return}try{campaigns=await getCampaigns();if(path.startsWith('/c/')){const slug=decodeURIComponent(path.slice(3));const campaign=campaigns.find(c=>c.published&&c.slug===slug);if(campaign)await editor(campaign);else{document.title='Campaign not found | Royal Cement';app.innerHTML='<div class="empty-state"><h1>Campaign not found</h1><p>This campaign may have ended or the link has changed.</p><a class="button primary" href="/">Browse campaigns</a></div>'}}else if(path==='/')home();else app.innerHTML='<div class="empty-state"><h1>Page not found</h1><a class="button" href="/">Back to campaigns</a></div>'}catch(e){showError(e.message)}}
start();
